# This is a config for E2B sandbox template.
# You can use 'template_id' (785n69crgahmz0lkdw9h) or 'template_name (azm_ai) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='azm_ai')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'azm_ai' })

dockerfile = "Dockerfile"
template_name = "azm_ai"
template_id = "785n69crgahmz0lkdw9h"
